# Generated by Django 6.0.4 on 2026-04-26 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
        ('tracking', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['user', 'start_time'], name='tracking_ti_user_id_450a84_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['task', 'start_time'], name='tracking_ti_task_id_263715_idx'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.UniqueConstraint(condition=models.Q(('end_time__isnull', True)), fields=('user',), name='unique_active_timer_per_user'),
        ),
    ]
